---
- hosts: test
  become: yes
  tasks:
  - name: install latest nano, vim, chromium, audacity, gimp, gparted
    dnf:
        name: "{{ item }}"
        state: latest
    loop:
        - nano 
        - vim-enhanced
        - chromium
        - audacity
        - gimp
        - gparted
